import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  ScrollView,
  SafeAreaView,
  FlatList,
  Alert,
} from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { useStore, QuoteRecord } from "../store/useStore";

const ExportScreen = () => {
  const {
    recentQuotes,
    businessName,
    setBusinessName,
    clearOldQuotes,
    profitMargin,
  } = useStore();

  const [selectedQuote, setSelectedQuote] = useState<QuoteRecord | null>(null);
  const [clientName, setClientName] = useState("");
  const [description, setDescription] = useState("");
  const [invoiceDate, setInvoiceDate] = useState(new Date().toLocaleDateString());
  const [isDetailed, setIsDetailed] = useState(true);

  useEffect(() => {
    clearOldQuotes();
  }, []);

  const generateHTML = () => {
    if (!selectedQuote) return "";

    const marginAmount = selectedQuote.baseCost * (profitMargin / 100);

    const breakdownRows = `
      <tr><td>Material Cost (${selectedQuote.materialName})</td><td class="amount">$${selectedQuote.materialCost.toFixed(2)}</td></tr>
      <tr><td>Electricity Cost</td><td class="amount">$${selectedQuote.electricityCost.toFixed(2)}</td></tr>
      <tr><td>Wear & Tear Fee</td><td class="amount">$${selectedQuote.wearAndTearCost.toFixed(2)}</td></tr>
      <tr><td>Profit Margin (${profitMargin}%)</td><td class="amount">$${marginAmount.toFixed(2)}</td></tr>
    `;

    const simpleRow = `
      <tr><td>Custom 3D Print - ${selectedQuote.materialName}</td><td class="amount">$${selectedQuote.finalQuote.toFixed(2)}</td></tr>
    `;

    return `
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
            .header { border-bottom: 2px solid #007AFF; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
            .business-name { font-size: 28px; font-weight: bold; color: #007AFF; }
            .invoice-info { text-align: right; }
            .invoice-title { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
            .client-section { margin-bottom: 40px; }
            .section-title { font-size: 14px; text-transform: uppercase; color: #666; margin-bottom: 5px; }
            .client-info { font-size: 18px; font-weight: 500; }
            .description { margin-bottom: 40px; font-style: italic; color: #555; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
            th { text-align: left; border-bottom: 1px solid #eee; padding: 10px; color: #666; }
            td { padding: 15px 10px; border-bottom: 1px solid #eee; }
            .amount { text-align: right; font-weight: 500; }
            .total-box { background: #f8f9fa; padding: 20px; border-radius: 8px; margin-left: auto; width: 50%; border: 1px solid #e9ecef; }
            .total-row { display: flex; justify-content: space-between; font-size: 20px; font-weight: bold; color: #007AFF; }
            .footer { margin-top: 50px; text-align: center; color: #999; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="business-name">${businessName || "Invoice"}</div>
            <div class="invoice-info">
              <div class="invoice-title">QUOTE</div>
              <div>Date: ${invoiceDate}</div>
            </div>
          </div>

          <div class="client-section">
            <div class="section-title">Prepared For</div>
            <div class="client-info">${clientName || "Valued Client"}</div>
          </div>

          ${description ? `<div class="description">${description}</div>` : ""}

          <table>
            <thead>
              <tr>
                <th>Description</th>
                <th class="amount">Total</th>
              </tr>
            </thead>
            <tbody>
              ${isDetailed ? breakdownRows : simpleRow}
            </tbody>
          </table>

          <div class="total-box">
            <div class="total-row">
              <span>Total Amount</span>
              <span>$${selectedQuote.finalQuote.toFixed(2)}</span>
            </div>
          </div>

          <div class="footer">
            Generated by 3D Print Quote Generator
          </div>
        </body>
      </html>
    `;
  };

  const handlePreview = async () => {
    const html = generateHTML();
    await Print.printAsync({ html });
  };

  const handleExport = async () => {
    const html = generateHTML();
    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri);
  };

  if (selectedQuote) {
    /* View B: Invoice Setup Form */
    return (
      <SafeAreaView style={styles.safeArea}>
        <ScrollView contentContainerStyle={styles.container}>
          <TouchableOpacity onPress={() => setSelectedQuote(null)} style={styles.backButton}>
            <Text style={styles.backButtonText}>← Back to History</Text>
          </TouchableOpacity>

          <Text style={styles.header}>Invoice Setup</Text>

          <View style={styles.section}>
            <View style={styles.inputGroup}>
              <Text style={styles.label}>Business / Your Name *</Text>
              <TextInput
                style={styles.input}
                value={businessName}
                onChangeText={setBusinessName}
                placeholder="e.g. Acme 3D Printing"
              />
              <Text style={styles.subtext}>Appears permanently on all invoices.</Text>
            </View>

            <View style={styles.inputGroup}>
              <Text style={styles.label}>Client Name (Optional)</Text>
              <TextInput
                style={styles.input}
                value={clientName}
                onChangeText={setClientName}
                placeholder="e.g. John Doe"
              />
            </View>

            <View style={styles.inputGroup}>
              <Text style={styles.label}>Project Description (Optional)</Text>
              <TextInput
                style={[styles.input, { height: 80 }]}
                value={description}
                onChangeText={setDescription}
                placeholder="e.g. Custom Prototype Part"
                multiline
              />
            </View>

            <View style={styles.inputGroup}>
              <Text style={styles.label}>Invoice Date *</Text>
              <TextInput
                style={styles.input}
                value={invoiceDate}
                onChangeText={setInvoiceDate}
              />
            </View>
          </View>

          <Text style={styles.sectionTitle}>Invoice Type</Text>
          <View style={styles.toggleRow}>
            <TouchableOpacity
              onPress={() => setIsDetailed(true)}
              style={[styles.toggleBtn, isDetailed && styles.toggleBtnActive]}
            >
              <Text style={[styles.toggleBtnText, isDetailed && styles.toggleBtnTextActive]}>Detailed</Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => setIsDetailed(false)}
              style={[styles.toggleBtn, !isDetailed && styles.toggleBtnActive]}
            >
              <Text style={[styles.toggleBtnText, !isDetailed && styles.toggleBtnTextActive]}>Simple</Text>
            </TouchableOpacity>
          </View>

          <TouchableOpacity style={styles.previewBtn} onPress={handlePreview}>
            <Text style={styles.previewBtnText}>Preview PDF</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.exportBtn} onPress={handleExport}>
            <Text style={styles.exportBtnText}>Export & Save PDF</Text>
          </TouchableOpacity>
        </ScrollView>
      </SafeAreaView>
    );
  }

  /* View A: Recent Quotes List */
  return (
    <SafeAreaView style={styles.safeArea}>
      <View style={styles.container}>
        <Text style={styles.header}>Recent Calculations</Text>
        <Text style={styles.subHeader}>12-Hour History</Text>

        {recentQuotes.length === 0 ? (
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyText}>No recent calculations.</Text>
            <Text style={styles.emptySubText}>Go to the Calculator tab to plan a print!</Text>
          </View>
        ) : (
          <FlatList
            data={recentQuotes}
            keyExtractor={(item) => item.id}
            renderItem={({ item }) => (
              <TouchableOpacity style={styles.quoteCard} onPress={() => setSelectedQuote(item)}>
                <View style={styles.quoteCardHeader}>
                  <Text style={styles.materialName}>{item.materialName}</Text>
                  <Text style={styles.quotePrice}>${item.finalQuote.toFixed(2)}</Text>
                </View>
                <View style={styles.quoteCardFooter}>
                  <Text style={styles.quoteDate}>
                    {new Date(item.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </Text>
                  <Text style={styles.quoteDetails}>
                    {item.printTime}h • {item.modelWeight}{item.unit}
                  </Text>
                </View>
              </TouchableOpacity>
            )}
            contentContainerStyle={{ paddingBottom: 20 }}
          />
        )}
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f5f5f5" },
  container: { flex: 1, padding: 16 },
  header: { fontSize: 24, fontWeight: "bold", color: "#333", marginBottom: 4 },
  subHeader: { fontSize: 14, color: "#666", marginBottom: 20 },
  emptyContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  emptyText: { fontSize: 18, fontWeight: "bold", color: "#999" },
  emptySubText: { fontSize: 14, color: "#999", marginTop: 8 },
  quoteCard: { backgroundColor: "#fff", padding: 16, borderRadius: 10, marginBottom: 12, borderWidth: 1, borderColor: "#e0e0e0" },
  quoteCardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  materialName: { fontSize: 18, fontWeight: "bold", color: "#333" },
  quotePrice: { fontSize: 18, fontWeight: "bold", color: "#007AFF" },
  quoteCardFooter: { flexDirection: "row", justifyContent: "space-between" },
  quoteDate: { color: "#888", fontSize: 12 },
  quoteDetails: { color: "#888", fontSize: 12 },
  
  /* Setup View Styles */
  backButton: { marginBottom: 15 },
  backButtonText: { color: "#007AFF", fontWeight: "bold", fontSize: 16 },
  section: { backgroundColor: "#fff", padding: 16, borderRadius: 8, borderWidth: 1, borderColor: "#e0e0e0", marginBottom: 16 },
  sectionTitle: { fontSize: 18, fontWeight: "600", color: "#666", marginBottom: 12 },
  inputGroup: { marginBottom: 16 },
  label: { fontSize: 14, color: "#444", marginBottom: 6 },
  input: { borderWidth: 1, borderColor: "#ccc", borderRadius: 4, padding: 12, fontSize: 16, backgroundColor: "#fff" },
  subtext: { fontSize: 12, color: "#999", marginTop: 4 },
  toggleRow: { flexDirection: "row", marginBottom: 24, borderRadius: 8, overflow: "hidden", borderWidth: 1, borderColor: "#007AFF" },
  toggleBtn: { flex: 1, padding: 12, alignItems: "center", backgroundColor: "#fff" },
  toggleBtnActive: { backgroundColor: "#007AFF" },
  toggleBtnText: { color: "#007AFF", fontWeight: "bold" },
  toggleBtnTextActive: { color: "#fff" },
  previewBtn: { backgroundColor: "#6c757d", padding: 18, borderRadius: 8, alignItems: "center", marginBottom: 12 },
  previewBtnText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  exportBtn: { backgroundColor: "#28a745", padding: 18, borderRadius: 8, alignItems: "center" },
  exportBtnText: { color: "#fff", fontSize: 18, fontWeight: "bold" },
});

export default ExportScreen;
